//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevaAplicacionMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foros
    {
        public int foro_id { get; set; }
        public string foro_title { get; set; }
        public string foro_image { get; set; }
        public string foro_content { get; set; }
        public string foro_autor { get; set; }
        public Nullable<System.DateTime> foro_date { get; set; }
    }
}
